---

- set_fact:
    phpmyadmin_dir: phpMyAdmin-{{ phpmyadmin_version }}-all-languages
    # ansible.builtin.unarchive needs gnu tar which isn't available on macOS
    phpmyadmin_zip: phpMyAdmin-{{ phpmyadmin_version }}-all-languages.zip

- name: Check if files/{{ phpmyadmin_dir }} exists
  become: no
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ phpmyadmin_dir }}"
  register: phpmyadmin_dir_stat

- name: Get local copy of {{ phpmyadmin_zip }}
  become: no
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/{{ phpmyadmin_zip }}
    dest: "{{ role_path }}/files/{{ phpmyadmin_zip }}"
  when: not phpmyadmin_dir_stat.stat.exists

- name: Extract {{ phpmyadmin_zip }}
  become: no
  delegate_to: localhost
  ansible.builtin.unarchive:
    src: "{{ role_path }}/files/{{ phpmyadmin_zip }}"
    dest: "{{ role_path }}/files"
    creates: files/{{ phpmyadmin_dir }}
  when: not phpmyadmin_dir_stat.stat.exists

- name: Copy config.inc.php (local)
  become: no
  local_action:
    module: copy
    src: config.inc.php
    dest: "{{ role_path }}/files/phpMyAdmin-{{ phpmyadmin_version }}-all-languages/"

- name: rsync phpmyadmin
  synchronize:
    src: files/phpMyAdmin-{{ phpmyadmin_version }}-all-languages/
    dest: /usr/local/share/phpmyadmin/
    owner: no
    delete: yes
    rsync_opts:
      - "--exclude=setup/"

- name: Create /etc/phpmyadmin/conf.d/
  file: state=directory path=/etc/phpmyadmin/conf.d/

- stat: path=/etc/phpmyadmin/conf.d/blowfish_secret.inc.php
  register: blowfish_secret_file

- name: Create secret for blowfish_secret.inc.php
  shell: openssl rand -base64 32 | cut -b -32
  register: blowfish_secret
  when: blowfish_secret_file.stat.exists == False

- name: Create blowfish_secret.inc.php
  copy:
    content: "<?php\n$cfg['blowfish_secret'] = '{{ blowfish_secret.stdout }}';\n?>"
    dest: /etc/phpmyadmin/conf.d/blowfish_secret.inc.php
    owner: root
    group: phpmyadmin
    mode: '0640'
  when: blowfish_secret_file.stat.exists == False

- name: Ensure access to blowfish_secret.inc.php
  file:
    path: /etc/phpmyadmin/conf.d/blowfish_secret.inc.php
    owner: root
    group: phpmyadmin
    mode: '0640'

- name: Create local-mit-phpmyadmin.include
  template:
    src: local-mit-phpmyadmin.include
    dest: /etc/nginx/conf.d/
  notify: Reload nginx

- name: Check deprecated files
  command: find /etc/nginx/conf.d/ -name mit-phpmyadmin.include
  register: cmd_ls
  failed_when: cmd_ls.stdout
  changed_when: no

