<?php
/**
 * Managed by ansible (mit.nginx.phpmyadmin)
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 */

$cfg['TempDir'] = '/tmp';

foreach (glob('/etc/phpmyadmin/conf.d/*.php') as $filename) {
    include($filename);
}

?>

